[package]
name = "ralsa"
version = "0.1.0"
edition = "2021"

[dependencies]
alsa = "0.6"
# alsa = { path = "../alsa-rs" }
alsa-sys = "0.3.1"

nix = "0.24"
clap = { version = "3.1.18", features = ["derive"] }
bitflags = "1.3.2"

udev = "0.6.3"

[[bin]]
name = "aseqdump"

[[bin]]
name = "aplaymidi"
